### ISSUE TITLE
minor edits and code polish

### ISSUE THREAD

**Issue by DickBaker** [JeremyLikness/PlanetaryDocs#10]
this GH project featured on EF Community Standup on 16/6/21
"Entity Framework Community Standup - Azure Cosmos DB and EF Core"  at
https://www.youtube.com/watch?v=nEqH_XfCfho
https://www.theurlist.com/efcore-standup-2021-06-16

Jeremy developed the project as example for CRUD with CosmosDb, and the Standup contrasted relational vs NoSql
 - this Issue is just preamble to my PR to fix some spelling mistakes, and code observations [analyzer suggestions]

HTH !

**Comment by JeremyLikness** [comment]
Thanks, this is appreciated.
