### ISSUE TITLE
Use of linq Intersect method

### ISSUE THREAD

**Issue by sandmanager** [JeremyLikness/PlanetaryDocs#13]
I am new to Cosmos DB and so even though I have been using EF for years the transition has been difficult. I hope you will be able to reproduce the following problem. I have worked with this for several days without success.

In the DocumentService.cs file I make a call to the QueryDocumentAsync method on line 68.

var result = await _documentService.QueryDocumentsAsync("", "scaddie", "Blazor");

The following gives me the correct number of authorAlias'
var author = await context.FindMetaAsync<Author>(authorAlias); (line 82)

I get a full list of all the tags 
var tagEntity = await context.FindMetaAsync<Tag>(tag);  (line 94)

I get the correct number of DocumentSummary from the Intersect call on line 99
resultSet = result.Intersect(tagEntity.Documents);

What I don't understand is that when result.Clear(); is called this also empties my resultset so that when the following foreach is call the result is always empty.
foreach (var docSummary in resultSet)  (line 108)
{
       result.Add(docSummary);   (this is never called because the resultSet is empty)
}
 
Thanks

**Comment by JeremyLikness** [comment]
When you call "Intersect" you are providing instructions for how the query will behave. The intersection isn't actually computed, it's just added to an expression tree as a set of instructions. The instructions are only "read" when you materialize the results in some way. The code you described does this:

"When I ask for results, give me the intersection of `result` and `tagEntity.Documents.`" Then you clear result. Then you say, "OK, give me the first result" and the query evaluates the instructions: the intersection of nothing (`result`) and `tagEntity.Documents` is... nothing. This is called _deferred execution_ if you want to learn more.

If you add a "ToList()" after "Intersect" then you materialize the results immediately, so the data should be preserved for your loop.
