### ISSUE TITLE
Feature request: More Documentation Please

### ISSUE THREAD

**Issue by siegfried01** [JeremyLikness/PlanetaryDocs#14]
I have some questions after studying this sample code.

1. Why is the property function called with a value of "PartitionKey" for docModel, tagModel and authorModel? Does it have anything to do with the Etag? [Where is the documentation for this property function overload that only accepts a single string?](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1.property?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.Property%60%601);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-5.0).
2. Please explain the usage patterns and partitioning decisions. For example: Why does the tagModel and the authorModel have a constant partition key of "PartitionKey"? I guess this means the tagModel and the authorModel are sharing the same partition called PartitionKey because when we access one we access the other? (Is this true?) I'm wondering if this tutorial could benefit from different choice of names ... Maybe TagAuthorModelParition instead of "PartitionKey"? Is this not going to be a problem if we get a lot of tags and authors (>20GB)?
3. Now when single stepping with the debugger at [DocumentService.cs](https://github.com/JeremyLikness/PlanetaryDocs/blob/main/PlanetaryDocs.DataAccess/DocumentService.cs) (line 174) in function SearchTagsAsynch Jeremy is calling a function ComputePartitionKey which returns partitionKey of "Tag" which is the name of the class. Why are we specifying a different partition key? I thought partition keys were ideally a unique itemed field that was specified inside OnModelCreating insdie the Context class. Why are we specifying a partition key again? Why is it constant (again)? Why are we specifying any partitionkey at all for a query? It looks to me like we have the same mystery logic for SearchAuthorsAsync. I see in the[ documentation for WithPartitionKey](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1?view=efcore-5.0#extension-methods) that this is "required when using a resource token that provides permission based on a partition key for authentication". Is Jeremy using a resource token for authentication? If so, please point me to this resource token in the source because I have not found it. Might a resource token be a JWT from AAD?
4. Why does not DocumentSummaries appear in the OnModelCreating in DocumentContext.cs?
Thanks
Siegfried & Bob

**Comment by JeremyLikness** [comment]
1. In CosmosDB, everything has a partition key and a primary key. The primary key uniquely identifies the document while the partitionkey specifies how data should be stored and synchronized across nodes. The constant specifies the _name_ of the property (`PartitionKey`) which is going to be the same for any Cosmos DB document. The _value_ of the partition key changes and happens to be the typename (i.e. "Author" or "Tag"). The documentation is on the non-generic method [here](https://docs.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.property?view=efcore-5.0#microsoft-entityframeworkcore-metadata-builders-entitytypebuilder-property(system-string)).
2. As explained in (1), the properties are the same but the values are different. Essentially authors are stored on one partition, tags another. This allows us to query either without the overhead of a [cross-partition query](https://docs.microsoft.com/azure/cosmos-db/sql/how-to-query-container#cross-partition-query). You can learn more here: [Cosmos DB partitions](https://docs.microsoft.com/azure/cosmos-db/partitioning-overview).
3. The partition key is passed so Cosmos DB doesn't have to cross partitions, making it faster and less expensive.
4. DocumentSummaries is owned by the related documents so there is no need for special configuration. EF Core automatically discovers nested complex types and includes them in the document.

In case you haven't read it yet, I wrote a [detailed blog post](https://blog.jeremylikness.com/blog/azure-cosmos-db-with-ef-core-on-blazor-server/).

**Comment by siegfried01** [comment]
Jeremey,
Thanks!  I understand it! Yahoo!

Another question: When studying PlanetaryDocs/DocsContext.cs at main · JeremyLikness/PlanetaryDocs (github.com)<https://github.com/JeremyLikness/PlanetaryDocs/blob/main/PlanetaryDocs.DataAccess/DocsContext.cs> line 96, I see you are passing the key and the partition key to FindAsync. When I look at the documentation for FindAsync I see that the two arguments are interpreted as primary keys which in the case of a tag of "astronomy" results in a primary key of "astronomyTag"... Why do you provide this second argument called "PartitionKey" to FindAsync? Since the tags have their own partition, why is not a primary key of "astronomy" sufficient?

Thanks Again!

Siegfried
[https://repository-images.githubusercontent.com/355640401/e9a05380-a131-11eb-83cc-b9fb9cbc4df3]<https://github.com/JeremyLikness/PlanetaryDocs/blob/main/PlanetaryDocs.DataAccess/DocsContext.cs>
PlanetaryDocs/DocsContext.cs at main · JeremyLikness/PlanetaryDocs · GitHub<https://github.com/JeremyLikness/PlanetaryDocs/blob/main/PlanetaryDocs.DataAccess/DocsContext.cs>
A complete Blazor Server app using Azure Cosmos DB with EF Core. - PlanetaryDocs/DocsContext.cs at main · JeremyLikness/PlanetaryDocs
github.com


________________________________

**Comment by JeremyLikness** [comment]
`FindAsync` is called for both tags and authors, so the partition key acts as a discriminator for `FindAsync` to know which partition to query.

**Comment by siegfried01** [comment]
Good morning Jeremy!

Your previous email says tags are stored in one partition and tags in another. Good!


  1.  So if tags and authors have their own partitions, why do we need a discriminator when calling FindAsync inside function FindMetaAsync?
  2.  How and when does Entity Framework Core (and Cosmos SDK) create separate partitions for tags and authors? I see on line 178 of the function OnModelCreating in file DocsContext.cs that you are calling HasPartitionKey but this property does not get a value until later. Can I conclude that the partitions for tags and authors are not defined until executing PlanetaryDocs/DocumentService.cs at main · JeremyLikness/PlanetaryDocs (github.com)<https://github.com/JeremyLikness/PlanetaryDocs/blob/main/PlanetaryDocs.DataAccess/DocumentService.cs> lines 393 and 451 where the partition key property is being set to "Tag" for tags and "Author" for authors?

Thank you very much for such a prompt response!

Siegfried
________________________________
